# Generated by Django 3.2.10 on 2022-01-09 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('youtube_url', models.URLField()),
                ('twitter_title', models.CharField(max_length=100)),
                ('twitter_consumer_key', models.CharField(max_length=100)),
                ('twitter_consumer_secret', models.CharField(max_length=100)),
                ('twitter_access_token', models.CharField(max_length=100)),
                ('twitter_access_token_secret', models.CharField(max_length=100)),
                ('twitter_bearer_token', models.CharField(max_length=200)),
                ('instagram_title', models.CharField(max_length=50)),
                ('facebook_title', models.CharField(max_length=50)),
                ('fb_access_token', models.CharField(max_length=250)),
                ('fb_client_id', models.CharField(max_length=50)),
                ('fb_client_secret', models.CharField(max_length=100)),
                ('fb_graph_domain', models.CharField(default='https://graph.facebook.com/', max_length=100)),
                ('fb_graph_version', models.CharField(default='v12.0', max_length=50)),
                ('fb_page_id', models.CharField(max_length=50)),
                ('fb_instagram_account_id', models.CharField(max_length=50)),
                ('fb_ig_username', models.CharField(max_length=50)),
                ('instagram_business_id', models.CharField(max_length=50)),
                ('linkedIn_title', models.CharField(max_length=50)),
                ('linkedIn_title_username', models.CharField(max_length=100)),
                ('linkedIn_title_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yt.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='c_users', through='yt.Link', to=settings.AUTH_USER_MODEL),
        ),
    ]
