# Generated by Django 3.2.10 on 2022-01-09 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='allowed_users',
            field=models.ManyToManyField(related_name='c_users', through='yt.Link', to=settings.AUTH_USER_MODEL),
        ),
    ]
