# Generated by Django 3.2.10 on 2022-02-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0002_alter_client_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='twetter_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
